version: '3.8'

services:
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: unless-stopped

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb+srv://mikelelabar:ferrara@cluster0.94sr5.mongodb.net/Database_foto
    ports:
      - "3001:3001"
    restart: unless-stopped