services:
  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://mikelelabar:ferrara@cluster0.94sr5.mongodb.net/Database_foto

  - type: web
    name: frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: ""
    startCommand: ""
